SaaS_System/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/',include("proj.urls",namespace="project")),
    path('users/',include('users.urls',namespace="users")),
    path("index/", TemplateView.as_view(template_name="../templates/index.html"), name="index"),
    path("mdeditor/",include("mdeditor.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/urls.py
from django.urls import path,include

from .views import project,proj_manage,wiki
app_name = "project"
urlpatterns = [
    # 项目列表
    path("list/", project.ProjectView.as_view(), name="project_list"),
    path("add_star/",project.addStar,name="addstar"),
    path("cancel_star/",project.cancelStar,name="cancelStar"),

    # 项目管理 完成项目才是关键
    path("manage/<project_id>/dashboard/", proj_manage.dashboard, name="dashboard"),
    path("manage/<project_id>/issues/", proj_manage.issues, name="issues"),
    path("manage/<project_id>/statistics/", proj_manage.statistics, name="statistics"),
    path("manage/<project_id>/file/", proj_manage.file, name="file"),

    path("manage/<project_id>/wiki/", wiki.wiki, name="wiki"),
    path("manage/<project_id>/wiki/upload/", wiki.wiki_upload, name="wiki_upload"),
    path("manage/<project_id>/wiki/add/",wiki.Wiki_add.as_view(),name="wiki_add"),
    path("manage/<project_id>/wiki/catalog/",wiki.wiki_catalog,name="wiki_catalog"),
    path("manage/<project_id>/wiki/delete/<del_id>",wiki.wiki_delete,name="wiki_delete"),
    path("manage/<project_id>/wiki/edit/<wiki_id>",wiki.EditWiki.as_view(),name="edit_wiki"),

    path("manage/<project_id>/setting/", proj_manage.setting, name="setting"),

]

users/urls.py
#coding:utf-8


from django.urls import path

from users.views import account

app_name = "users"
urlpatterns = [
    path('register/', account.RegisterView.as_view(), name="register"), #注册
    path('send_code/', account.sendcode, name="sendcode"),#获取验证码
    path('emaillogin/',account.EmailLoginView.as_view(),name="emaillogin"), #邮箱登录
    path('pswdlogin/',account.PswdLoginView.as_view(),name="pswdlogin"), #密码登录
    path("verify_img/",account.verify_picture,name="verify_picture"),
    path("logout/",account.logout,name="logout")
]

users/models.py
from django.db import models

# Create your models here.
from proj.models import Project,PricePolicy

class UserInfo(models.Model):

    username = models.CharField(verbose_name="用户名",max_length=32)
    email = models.CharField(verbose_name="邮箱",max_length=32,unique=True)
    mobile_phone = models.CharField(verbose_name="手机号",max_length=11,unique=True)
    password = models.CharField(verbose_name="密码",max_length=100)
    price_policy = models.ForeignKey("proj.PricePolicy",on_delete=models.CASCADE,default=1)
    project_num = models.SmallIntegerField(verbose_name="项目个数",default=0)

    class Meta:
        db_table = "userprofile"
        verbose_name = "用户表"
        verbose_name_plural = verbose_name

users/forms/account.py
#coding:utf-8

from django import forms
from users import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from forms.base_bootstrap import Base_Bootstrap
from users.utils.redisTool import storageCode_Toredis,getCode_FromRedis
from users.utils.sendCode import send_EmailCode
from users.utils.timeManager import oneHourMaxClickNumber
import random
from django.contrib.auth.hashers import make_password


class RegisterForm(Base_Bootstrap,forms.ModelForm):


    password = forms.CharField(label="密码",
       min_length=8,
       max_length=16,
       error_messages={
        "min_length":"密码长度不能小于8位",
        "max_length":"密码长度不能大于16位"
    },widget=forms.PasswordInput())

    confirm_password = forms.CharField(label="重复密码",
       min_length=8,
       max_length=16,
       error_messages={
        "min_length":"重复密码长度不能小于8位",
        "max_length":"密码长度不能大于16位"
    },widget=forms.PasswordInput())
    mobile_phone = forms.CharField(label="手机号", validators=[RegexValidator(r'(1[3|4|5|6|7|8|9]\d{9})', "手机号格式错误"), ])  # 走正则表达式
    code = forms.CharField(label="验证码", widget=forms.TextInput())


    class Meta:
        model = models.UserInfo
        fields = ["username","email","mobile_phone","password","confirm_password","code"]
        # fields = ["mobile_phone",]

    def clean_username(self):
        username = self.cleaned_data.get("username")
        exists = models.UserInfo.objects.filter(username=username).exists()
        if exists:
            raise ValidationError("用户名已存在")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        exists = models.UserInfo.objects.filter(email=email).exists()

        if exists:
            raise ValidationError("邮箱已存在")
        return email

    def clean_mobile_phone(self):
        mobile_phone = self.cleaned_data.get("mobile_phone")
        exists = models.UserInfo.objects.filter(mobile_phone=mobile_phone).exists()
        if exists:
            raise ValidationError("手机号已注册")
        if len(mobile_phone) < 11 or len(mobile_phone) >11:
            raise ValidationError("手机号码不对哦~")
        return mobile_phone

    def clean_password(self):
        pswd = self.cleaned_data.get("password","")

        encrytion_paswd = make_password(pswd,"pbkdf2_sha256")
        # print(" in password",encrytion_paswd)
        return encrytion_paswd

    def clean_confirm_password(self):
        pswd = self.cleaned_data.get("password","")
        confirm_pswd = self.cleaned_data.get("confirm_password","")
        encrytion_confirm_pswd = make_password(confirm_pswd,"pbkdf2_sha256")

        #如果要校验confirm_password 那么
        if pswd != encrytion_confirm_pswd:
            raise ValidationError("两次密码不一致")
        # print("in confirm_password",encrytion_confirm_pswd)
        return encrytion_confirm_pswd


    def clean_code(self):
        code = self.cleaned_data.get("code","")
        email = self.cleaned_data.get("email","")
        #验证邮箱验证码

        redis_code = getCode_FromRedis(email)
        if not redis_code:
            raise ValidationError("验证码失效,请重新发送~")

        if code.strip() != redis_code:
            raise ValidationError("验证码错误")

        return code




class SendEmailCodeForm(forms.Form):#验证码模块

    email = forms.EmailField(label="邮箱")

    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request = request

    def clean_email(self):
        no_valid_email = self.cleaned_data.get("email")
        # exists = models.UserInfo.objects.filter(email=no_valid_email).exists()

        # if exists:
        #     # self.add_error() 两者报错一样 这个报错了下面的还会继续执行
        #     raise ValidationError("邮箱已经存在")#这个出错了就会抛出异常 不会执行下面的动作


        #如果不对邮箱进行验证的话会出现什么情况呢？
        #
        # 1.用户在注册的时候，邮箱本来就是不存在的
        # 2.用户在登录的时候,如果邮箱不存在那么直接跳到注册页面即可!

        result = oneHourMaxClickNumber(no_valid_email+"_")
        if result == True:#一个小时内最大的点击次数

            code = random.randrange(10000,99999)
            tpl = self.request.POST.get("tpl")
            if tpl == "register":
                result = storageCode_Toredis(no_valid_email,code,tpl=tpl) #存储生成的验证码在数据库
                if result == True:
                    send_EmailCode(no_valid_email,code,tpl)
            elif tpl == "login":
                result = storageCode_Toredis(no_valid_email, code, tpl=tpl)  # 存储生成的验证码在数据库
                if result == True:
                    send_EmailCode(no_valid_email, code, tpl)
        else:
            raise ValidationError("对不起,您在一个小时内发送的请求过多,请稍后重试")
        return no_valid_email



class EmailLoginForm(Base_Bootstrap,forms.Form): # 登录
    email = forms.EmailField(label="邮箱",widget=forms.EmailInput())
    code = forms.CharField(label="验证码",widget=forms.TextInput())

    class Meta:
        model = models.UserInfo
        fields = ["email","code"]


    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_obj = models.UserInfo.objects.filter(email=email) #直接返回这个对象，省一次查询
        if user_obj.exists():
            return user_obj.first()
        raise ValidationError("邮箱不存在，请前往注册")

    def clean_code(self):
        no_virify_code = self.cleaned_data.get("code")
        user_obj = self.cleaned_data.get("email")
        if not user_obj:
            raise ValidationError("用户不存在,请重新注册")
        # 多层捕捉错误,提高程序的容错率和健壮性
        code = getCode_FromRedis(user_obj.email)
        if no_virify_code != code:
            raise ValidationError("验证码错误")
        return code



class LoginForm(Base_Bootstrap,forms.Form):

    email = forms.CharField(label="手机号或邮箱")

    password = forms.CharField(label="密码",
                               min_length=8,
                               max_length=16,
                               error_messages={
                                   "min_length": "密码长度不能小于8位",
                                   "max_length": "密码长度不能大于16位"
                               }, widget=forms.PasswordInput())
    code = forms.CharField(label="图片验证码", widget=forms.TextInput())


    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)#
        self.request = request

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if len(email) == 11 :
            result = models.UserInfo.objects.filter(mobile_phone=email).exists()
            if result :
                return email
            raise ValidationError("手机号不存在,请返回注册")
        elif "@" in email:
            result = models.UserInfo.objects.filter(email=email).exists()
            if result:
                return email
            raise ValidationError("邮箱不存在,请返回注册")

    def clean_password(self):

        pswd = self.cleaned_data.get("password")
        userpswd =  make_password(pswd,"pbkdf2_sha256")

        return userpswd


    def clean_code(self):

        code = self.cleaned_data.get("code")
        session_code = self.request.session.get("image_code")
        if not session_code:
            raise ValidationError("验证码已过期，请重新获取")
        if code.strip().upper() != session_code.strip().upper():
            raise ValidationError("验证码输入错误")

        return code

users/views/account.py
#coding:utf-8
import datetime

from django.shortcuts import render,HttpResponse,redirect
# 用户账号管理的功能!
# Create your views here.
from proj.utils.tools import gen_order_id
from django import forms
from users import models
from django.db.models import F,Q
from users.forms.account import RegisterForm,EmailLoginForm,SendEmailCodeForm,LoginForm
from django.views import View
from django.http import JsonResponse
from users.utils.genRandomCodeImage import BigPainter
from proj.models import Transaction,PricePolicy


class RegisterView(View): #注册

    def get(self,request):
        forms = RegisterForm()
        return render(request,"register.html",{"forms":forms})

    def post(self,request):
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            price_object = PricePolicy.objects.filter(category=1,title="个人免费版").first()

            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            phone = form.cleaned_data.get("mobile_phone")
            pswd = form.cleaned_data.get("password")



            user = models.UserInfo.objects.create(
                username=username,
                email=email,
                password=pswd,
                mobile_phone=phone,
                price_policy=price_object,

            )

            # print("已验证:",form.cleaned_data)

            # instance = form.save()



            Transaction.objects.create(
                    status=1,
                    order_id=gen_order_id(),
                    user=user,
                    price_policy_id= price_object.id,
                    count=0,
                    price=0,
                    start_datetime=datetime.datetime.now()

            )
            return JsonResponse({"status":True})

        return JsonResponse({"status":False,"error":form.errors})




class EmailLoginView(View): #邮箱验证码登录

    def get(self,request):
        forms = EmailLoginForm()
        return render(request, "emaillogin.html", {"forms":forms})

    def post(self,request):

        form = EmailLoginForm(data=request.POST)
        if form.is_valid():
            #将用户信息放入session
            user_obj = form.cleaned_data.get("email","")
            request.session["user_id"] = user_obj.id
            request.session.set_expiry(60*60*24*14)
            return JsonResponse({"status":True})
        return JsonResponse({"status":False,"error":form.errors})



class PswdLoginView(View): #密码登录

    def get(self,request):
        form  = LoginForm(request)
        return render(request,"pswdlogin.html",{"forms":form})

    def post(self,request):
        form = LoginForm(request,data=request.POST)

        if form.is_valid():
            user_email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user_obj = models.UserInfo.objects.filter(Q(email=user_email)|Q(mobile_phone=user_email)).filter(password=password).first()

            if user_obj:
                request.session["user_id"] = user_obj.id
                request.session.set_expiry(60 * 60 * 24 * 14)
                return JsonResponse({"status":True})
            form.add_error("email","用户名或者密码错误")
        return JsonResponse({"status":False,"error":form.errors})



def sendcode(request):
    form = SendEmailCodeForm(request,data=request.POST)
    if form.is_valid():
        return JsonResponse({"status":True,"msg":"验证码发送成功!",})
    return JsonResponse({"status":False,"error":form.errors})

def verify_picture(request):
    from io import BytesIO
    image,code = BigPainter.Draw()
    request.session["image_code"] = None #先初始化...不然会爆KeyError的错误
    request.session["image_code"] = code
    request.session.set_expiry(60)#60s 过期
    stream = BytesIO()
    # print(request.session.get("image_code"))
    image.save(stream,"png")

    return HttpResponse(stream.getvalue())


def logout(request):
    request.session.flush()
    return redirect("users:pswdlogin")

users/templates/emaillogin.html
{% extends 'layout/basic.html' %}

{% load static %}
{% block title %}用户登录{% endblock %}
{% block css %}
        <link rel="stylesheet" href="{% static 'plugin/bootstrap/3.4.1.bootstrap.min.css' %}">
   <script rel="script" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script rel="script" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg{
            color:red
        }

    </style>
{% endblock %}
{% block content %}
    <div class="container">

    </div>
      <div class="account">
        <h1 class="text-center">邮箱验证码登录</h1>
        <form id="LogForm" >
        {% csrf_token %}
              {% for field in forms %}
                  {% if field.name == 'code' %}
                       <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      <div class="clearfix">
                        <div class="col-md-6" style="padding-left:0">{{ field }}
                         <span class="error-msg"></span></div>
                        <div class="col-md-6">
                            <button  id="btnSendCode" onclick="sendEmailCode()" class="btn btn-default">点击获取验证码</button>
                        </div>
                      </div>
                  {% else %}
                   <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                   <span class="error-msg"></span>
                   </div>
                  {% endif %}
           {% endfor %}
            <button type="button" style="margin-top:25px;" class="btn btn-primary" onclick="EmailLogin()">登 录</button>
            <a href="{% url 'users:pswdlogin' %}" style="margin-top:-25px;margin-left:270px;display: block; ">密码登录?</a>
        </form>

    </div>

{% endblock %}

{% block js %}
        <script>
        function sendEmailCode(){
            sendEmailRemind();
            $(".error-msg").empty();

           email = $("#id_email").val();
           var reg = /^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;
           if (reg.test(email)){
               $.ajax({
                   url: "{% url 'users:sendcode' %}",
                   async: true,
                   data: {"email": email,
                       tpl:"login",
                       csrfmiddlewaretoken: "{{ csrf_token }}"
                   },
                   type: "POST",
                   success: function (res) {
                        if (res.status){
                           alert(res["msg"]);

                       }else{

                           // 显示错误信息
                            $.each(res.error,function(key,value){ //.each()循环信息 将参数1的dict信息给进行循环
                                $("#id_"+key).next().text(value[0]);//
                            })
                       }
                   }
               });
               return true;
           }else{
               $("#id_email").next().text("您的邮箱不正确哦~");
               return false;
           }

        }
     function sendEmailRemind() {
            var $btnSendCode = $("#btnSendCode");
            $btnSendCode.prop("disabled", true);//禁用
            var time = 60;
            var remind = setInterval(function () {
                $btnSendCode.val(time + "秒后重新发送");
                time = time - 1;
                if (time < 0) {
                    clearInterval(remind);
                    $btnSendCode.val("点击获取验证码").prop("disabled",false);
                }
            }, 1000)

        }


    function EmailLogin(){

            $.ajax({
                url:"{% url 'users:emaillogin' %}",
                type:"POST",
                dataType:"JSON",
                data:$("#LogForm").serialize(),
                async:true,
                success:function(res){
                    if (res.status){
                        location.href="{% url 'index' %}"
                    }else{
                        $("#id_code").next().text(res.error.code[0]);
                    }
                }
            })
    }



    </script>

{% endblock %}

users/templates/pswdlogin.html
{% extends 'layout/basic.html' %}

{% load static %}
{% block title %}用户登录{% endblock %}
{% block css %}
        <link rel="stylesheet" href="{% static 'plugin/bootstrap/3.4.1.bootstrap.min.css' %}">
   <script rel="script" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script rel="script" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg{
            color:red
        }

    </style>
{% endblock %}
{% block content %}
    <div class="container">

    </div>
      <div class="account">
        <h1 class="text-center">密码登录</h1>
        <form id="LogForm" >
        {% csrf_token %}
              {% for field in forms %}
                  {% if field.name == 'code' %}
                       <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      <div class="clearfix">
                        <div class="col-md-6" style="padding-left:0">{{ field }}
                         <span class="error-msg"></span></div>

{#                        <div class="col-md-6"><input type="button" value="点击获取验证码" id="btnSendCode" onclick="sendEmailCode()" class="btn btn-default"></div>#}
                        <img src="{% url 'users:verify_picture' %}" id="ImgCode" title="点击更换图片">
                      </div>
                  {% else %}
                   <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                   <span class="error-msg"></span>
                   </div>
                  {% endif %}
           {% endfor %}
            <button type="button" style="margin-top:25px;" onclick="PasswordLogin()" class="btn btn-primary">登 录</button>
            <a href="{% url 'users:emaillogin' %}" style="margin-top:-25px;margin-left:240px;display: block; ">验证码登录?</a>
        </form>

    </div>

    <script>

    function PasswordLogin(){
            $(".error-msg").empty();
            $.ajax({
                url:"{% url 'users:pswdlogin' %}",
                type:"POST",
                dataType:"JSON",
                data:$("#LogForm").serialize(),
                async:true,
                success:function(res){
                    if (res.status){
                        location.href = "{% url 'index' %}";
                    }else{

                        $.each(res.error,function(key,value){ //.each()循环信息 将参数1的dict信息给进行循环
                                $("#id_"+key).next().text(value[0]);//
                            })
                    }
                }
            })
    }



    </script>



{% endblock %}



{% block js %}
    <script>
        $(function(){
            $("#ImgCode").click(function(){
               var OldSrc = $(this).attr("src");
               $(this).attr("src",OldSrc+"?");
            });

        })

    </script>
{% endblock %}

users/templates/register.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户注册{% endblock %}
{% block css %}
        <link rel="stylesheet" href="{% static 'plugin/bootstrap/3.4.1.bootstrap.min.css' %}">
   <script rel="script" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script rel="script" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
    .error-msg{
        color:red;
        position:absolute;
        font-size:13px;
    }

    #btnSendCode{

    }

    </style>
{% endblock %}
{% block content %}
    <div class="container">

    </div>
      <div class="account">
        <h1 class="text-center">用户注册</h1>
        <form id="regForm" method="post" >
        {% csrf_token %}
              {% for field in forms %}
                  {% if field.name == 'code' %}
                       <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      <div class="clearfix">
                            <div class="col-md-6" style="padding-left:0">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-6">
                                <input type="button" class="btn btn-default" value="点击获取验证码" id="btnSendCode" onclick="sendEmailCode()" >
                            </div>
                      </div>
                  {% else %}
                   <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                   </div>
                  {% endif %}
           {% endfor %}

            <button id="btnSubmit" type="button" style="margin-top:25px;margin-left:130px;" class="btn btn-primary" onclick="clickSubmitReg()">注 册</button>
            <a href="{% url 'users:pswdlogin' %}" style="margin-top:-25px;margin-left:270px;display: block; ">已有账号?</a>
        </form>

    </div>




{% endblock %}

{% block js %}

    <script>
    //整个页面框架加载完成之后，会执行
        function clickSubmitReg(){ //点击提交注册
            //收集表单的数据
            $(".error-msg").empty();
            /*

            username = $("#id_username").val();
            email = $("#id_email").val();
            mobile_phone = $("#id_mobile_phone").val();
            password = $("#id_password").val();
            confirm_password = $("#id_confirm_password").val();
            code = $("#id_code").val(); // 方式1
            */
            $("#regForm").serialize();//收集表单所有数据 但是有些数据是不需要的就可以使用第一种方法

            $.ajax({
                url:"{% url 'users:register' %}",
                type:"POST",
                data:$("#regForm").serialize(),
                dataType:"JSON",
                success:function(res){
                    console.log(res);
                    if (res.status){
                        location.href = "{% url 'users:pswdlogin' %}";
                    }else{
                        console.log(res.error);
                         $.each(res.error,function(key,value){

                             $("#id_" + key).next().text(value[0]);//
                            })
                    }
                }
            });


    }

            function sendEmailCode(){ // 点击获取发送邮箱验证码
                sendEmailRemind();
                $(".error-msg").empty();
             // 将已经存在于error-msg的信息清空
            // js命名规则是 驼峰式命名  example: mobilePhone
           var email = $("#id_email").val();
           var reg = /^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;
           if (reg.test(email)){
               $.ajax({
                   url: "{% url 'users:sendcode' %}",
                   async: true,
                   dataType:"JSON",
                   data: {email: email,
                   "csrfmiddlewaretoken":'{{ csrf_token }}',
                        tpl:"register",
                   },
                   type: "POST",
                   success: function (res) { // 自动回调(执行)函数

                       if (res.status){
                           alert(res["msg"]);
                           {#sendEmailRemind();#}
                       }else{

                           // 显示错误信息
                            $.each(res.error,function(key,value){ //.each()循环信息 将参数1的dict信息给进行循环
                                $("#id_"+key).next().text(value[0]);//
                            })
                       }
                   }

               });
               return true;
           }else{

               $(".error-msg").text("您的邮箱不正确哦~");
                return false;
           }
            }



        function sendEmailRemind() {
            var $btnSendCode = $("#btnSendCode");
            $btnSendCode.prop("disabled", true);//禁用

            var time = 60;
            var remind = setInterval(function () {
                $btnSendCode.val(time + "秒后重新发送");
                time = time - 1;
                if (time < 0) {
                    clearInterval(remind);
                    $btnSendCode.val("点击获取验证码").prop("disabled",false);
                }
            }, 1000)
        }



    </script>
{% endblock %}