SaaS_System/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/',include("proj.urls",namespace="project")),
    path('users/',include('users.urls',namespace="users")),
    path("index/", TemplateView.as_view(template_name="../templates/index.html"), name="index"),
    path("mdeditor/",include("mdeditor.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/urls.py
from django.urls import path,include

from .views import project,proj_manage,wiki
app_name = "project"
urlpatterns = [
    # 项目列表
    path("list/", project.ProjectView.as_view(), name="project_list"),
    path("add_star/",project.addStar,name="addstar"),
    path("cancel_star/",project.cancelStar,name="cancelStar"),

    # 项目管理 完成项目才是关键
    path("manage/<project_id>/dashboard/", proj_manage.dashboard, name="dashboard"),
    path("manage/<project_id>/issues/", proj_manage.issues, name="issues"),
    path("manage/<project_id>/statistics/", proj_manage.statistics, name="statistics"),
    path("manage/<project_id>/file/", proj_manage.file, name="file"),

    path("manage/<project_id>/wiki/", wiki.wiki, name="wiki"),
    path("manage/<project_id>/wiki/upload/", wiki.wiki_upload, name="wiki_upload"),
    path("manage/<project_id>/wiki/add/",wiki.Wiki_add.as_view(),name="wiki_add"),
    path("manage/<project_id>/wiki/catalog/",wiki.wiki_catalog,name="wiki_catalog"),
    path("manage/<project_id>/wiki/delete/<del_id>",wiki.wiki_delete,name="wiki_delete"),
    path("manage/<project_id>/wiki/edit/<wiki_id>",wiki.EditWiki.as_view(),name="edit_wiki"),

    path("manage/<project_id>/setting/", proj_manage.setting, name="setting"),

]

proj/models.py
from django.db import models

# Create your models here.


from mdeditor.fields import MDTextField


class PricePolicy(models.Model):# this is Teacher·wu create table
    category_choices = (
        (1,"免费版"),
        (2,"收费版"),
        (3,"其他")
    )
    category = models.SmallIntegerField(verbose_name="收费类型",default=1,choices=category_choices) #一开始应该是免费版
    title = models.CharField(verbose_name="标题",max_length=32)
    price = models.PositiveIntegerField(verbose_name="价格")
    project_num = models.PositiveIntegerField(verbose_name="项目数")
    project_member = models.PositiveIntegerField(verbose_name="项目成员数")
    project_space =models.PositiveIntegerField(verbose_name="单项目空间")
    pro_file_size =models.PositiveIntegerField(verbose_name="单文件大小")
    create_datetime = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)

    class Meta:
        db_table = "pricepolicy"
        verbose_name = "价格表"
        verbose_name_plural = verbose_name
class  Transaction(models.Model):#交易记录表
    status_code = (
        (0,"未支付"),
        (1,"已支付"),
    )
    status = models.SmallIntegerField(verbose_name="交易状态",choices=status_code)
    order_id = models.CharField(verbose_name="订单号",max_length=20,unique=True)
    user= models.ForeignKey("users.UserInfo",on_delete=models.CASCADE)
    price_policy = models.ForeignKey("PricePolicy",on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name="数量/年",help_text="0表示无限期",default=0)
    price = models.IntegerField(verbose_name="实际支付价格",default=0,help_text="0表示并未购买或者购买的已经过期")
    start_datetime = models.DateTimeField(verbose_name="服务开始时间",null=True,blank=True)
    end_datetime = models.DateTimeField(verbose_name="服务结束时间",null=True,blank=True)
    create_datetime = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)

    class Meta:
        db_table = "transaction"
        verbose_name = "交易表"
        verbose_name_plural = verbose_name


class Project(models.Model):
    COLOR_CHOICES = (
        (1,"#56b8eb"),
        (2,"#f28033"),
        (3,"#ebc656"),
        (4,"#a2d148"),
        (5,"#208fa4"),
        (6,"#7461c2"),
        (7,"#20bfa3")
    )
    name = models.CharField(verbose_name="项目名称",max_length=32)
    color = models.SmallIntegerField(verbose_name="项目颜色",choices=COLOR_CHOICES,default=1)
    desc = models.CharField(verbose_name="项目描述",max_length=255,null=True,blank=True)
    user_space = models.IntegerField(verbose_name="项目已使用空间",default=0)
    star = models.BooleanField(verbose_name="星标",default=False)
    join_count = models.SmallIntegerField(verbose_name="参与人数",default=1)
    creator = models.ForeignKey("users.UserInfo",on_delete=models.CASCADE,verbose_name="创建者")
    create_datetime = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)
    bucket = models.CharField(verbose_name="COS桶",max_length=128,default="")
    region = models.CharField(verbose_name="cos区域",max_length=32,default="ap-nanjing")


    class Meta:
        db_table = "project"
        verbose_name = "项目表"
        verbose_name_plural = verbose_name


class ProjectUser(models.Model):
    user = models.ForeignKey("users.UserInfo",on_delete=models.CASCADE)
    project = models.ForeignKey("Project",on_delete=models.CASCADE)
    star = models.BooleanField(default=False,verbose_name="星标")
    create_datetime = models.DateTimeField(verbose_name="加入时间",auto_now_add = True)

    class Meta:
        db_table = "projectuser"
        verbose_name = "项目参与者表"
        verbose_name_plural = verbose_name



class Wiki(models.Model):

    project = models.ForeignKey("Project",on_delete=models.CASCADE)
    title = models.CharField(verbose_name="标题",max_length=32)
    content = models.TextField(verbose_name="内容")
    parent = models.ForeignKey(verbose_name="父文章",to="self",on_delete=models.CASCADE,null=True,blank=True,related_name="children")
    depth = models.SmallIntegerField(verbose_name="深度",default=1)
    class Meta:
        db_table = "wiki"
        verbose_name = "项目说明"
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.title
# class PriceStrategy(models.Model): #this my create table
#
#     id = models.AutoField(primary_key = True,unique=True,verbose_name="策略id")
#     category = models.CharField(max_length=10,verbose_name="价格分类")
#     title = models.CharField(max_length=10,verbose_name="价格标题")
#     price = models.IntegerField(verbose_name="价格")
#     project_members = models.IntegerField(verbose_name="项目成员")
#     project_space = models.IntegerField(verbose_name="项目空间")
#     file_space = models.IntegerField(verbose_name="单个文件的空间")
#     #价格表不需要关联用户
#     class Meta:
#         db_table = "pricestrategy"
#         verbose_name = "价格策略表"
#         verbose_name_plural = verbose_name
#         ordering = ["project_members","project_space"]



# class Transaction(models.Model): #this my create table
#
#     # 交易表需要关联用户以及价格策略表
#     id = models.AutoField(primary_key=True,unique=True,verbose_name="交易id")
#     order_id = models.IntegerField(verbose_name="订单id",unique=True) #unique
#     state = models.CharField(max_length=20,verbose_name="交易状态")
#     user = models.ForeignKey("users.UserInfo",on_delete=models.CASCADE)
#     price_category = models.ForeignKey("PriceStrategy",on_delete=models.CASCADE)
#     actual_delivery = models.IntegerField(verbose_name="实际支付")
#     service_start_time = models.DateField(auto_now_add=True,verbose_name="服务开启时间")
#     service_end_time = models.DateField(verbose_name="服务结束时间") #得自行编写!
#     number = models.IntegerField(verbose_name="购买数量/年")
#
#     class Meta:
#         db_table = "transaction"
#         verbose_name = "交易表"
#         verbose_name_plural = verbose_name
#         ordering = ["number","id","order_id","actual_delivery"]

proj/forms/project.py
#coding:utf-8

from forms.base_bootstrap import Base_Bootstrap
from proj import models
from django import forms
from django.core.validators import ValidationError
from forms.widgets import ColorRadioSelect

class ProjectModelForm(Base_Bootstrap,forms.ModelForm):
    # desc = forms.CharField(widget=forms.Textarea())
    bootstrap_classs_exclude = ["color"]
    class Meta:
        model = models.Project
        fields = ["name","color","desc"]
        widgets = {
            "desc":forms.Textarea(),
            "color":ColorRadioSelect(attrs={"class":"color-radio"})

        }

    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request = request
    def clean_name(self):
        name = self.cleaned_data.get("name")
        exists = models.Project.objects.filter(name=name,creator=self.request.tracer.user).exists()


        """
        1.判断当前项目名称是否存在
        2.判断当前用户权限是否已经无法创建新的项目了
        3.判断该用户
        """
        if exists:
            raise ValidationError("该项目已存在")
        count = models.Project.objects.filter(creator=self.request.tracer.user).count()
        if count >= self.request.tracer.price_policy.project_num:
            raise ValidationError("项目个数超限,请购买套餐")
        return name

proj/forms/wiki.py
#coding:utf-8


from django import forms
from proj.models import Wiki
from forms.base_bootstrap import Base_Bootstrap

class WikiModelForm(Base_Bootstrap,forms.ModelForm):

    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request= request
        total_data_list = [("","请选择"),]
        data_list = Wiki.objects.filter(project=self.request.tracer.project).values_list("id","title")
        total_data_list.extend(data_list)
        self.fields["parent"].choices = total_data_list #显示父级文章选项和请选择标签

    class Meta:
        model = Wiki
        exclude = ["project","depth",]#过滤叼project 和 depth

proj/views/proj_manage.py
#coding:utf-8


from django.shortcuts import render


def dashboard(request,project_id):
    return render(request,"dashboard.html")

def issues(request,project_id):
    return render(request, "issues.html")


def statistics(request,project_id):
    return render(request, "statistics.html")

def file(request,project_id):
    return render(request, "file.html")


def setting(request,project_id):
    return render(request, "setting.html")

proj/views/project.py
import time

from django.shortcuts import render
from django.http import JsonResponse
# Create your views here.
from proj.forms.project import ProjectModelForm
from django.views import View
from proj.models import Project,ProjectUser
from users import models
from scripts.Tencent_COS import create_bucket

class ProjectView(View):
    # 1 从数据库中获取两部分的数据
    # 我创建的所有项目, 已星标 未星标
    # 我参与的所有项目  已星标 未星标

    # 2.提取已星标
    # 列表 = 循环 [我创建的所有项目] + [我参与的所有项目] 把已星标的数据提取
    # 然后就得到三个列表

    def get(self,request):
        form = ProjectModelForm(request)
        projects_dict = {"star":[],"my":[],"join":[]}
        my_projects = Project.objects.filter(creator = request.tracer.user)
        my_join_projects = ProjectUser.objects.filter(user=request.tracer.user)
        for proj in my_projects:
            if proj.star:
                projects_dict["star"].append(proj)
            else:
                projects_dict["my"].append(proj)

        for proj in my_join_projects:
            if proj.star:
                projects_dict["star"].append(proj.project)
            else:
                projects_dict["join"].append(proj.project)



        return render(request, "project_list.html", {"forms": form,"project_dict":projects_dict})

    def post(self,request):
        form = ProjectModelForm(request,data=request.POST)
        if form.is_valid():
            # 为项目创建一个桶
            bucket = "{}-{}".format(request.tracer.user.mobile_phone+"-"+form.instance.name,str(int(time.time())))
            region = "ap-nanjing"
            bucket_name = create_bucket(bucket,region)
            form.instance.bucket = bucket_name
            form.instance.creator = request.tracer.user
            request.tracer.user.project_num += 1 #项目数为你添加了多少个项目来进行判断
            request.tracer.user.save() #保存下即可!
            form.save()
            return JsonResponse({"status":True,})

        return JsonResponse({"status":False,"error":form.errors})


def addStar(request):

    proj_id = request.POST.get("addstar")

    result = Project.objects.filter(id=proj_id,creator=request.tracer.user).first()
    if result:
        result.star = True
        result.save()
        return JsonResponse({"status":True})
    return JsonResponse({"status":False})


def cancelStar(request):
    proj_id = request.POST.get("cancelstar")
    result = Project.objects.filter(id=proj_id,creator=request.tracer.user).first()
    if result:
        result.star = False
        result.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False})

proj/views/wiki.py
#coding:utf-8

from django.shortcuts import render,redirect,HttpResponse
from django.views import View
from proj.forms.wiki import WikiModelForm
from django.urls import reverse
from django.http import JsonResponse
from proj.models import Wiki
from scripts.Tencent_COS import upload_file
import string
from scripts.encrypt import uid

from django.views.decorators.csrf import csrf_exempt

def wiki_delete(request,project_id,del_id):

    if del_id:
        obj = Wiki.objects.filter(project_id=project_id,id=del_id).delete() #删除当前id内的wiki问题
        url = reverse("project:wiki", kwargs={"project_id": project_id})
        return redirect(url)


class EditWiki(View):



    def get(self,request,project_id,wiki_id):
        wiki_object = Wiki.objects.filter(project_id=project_id, id=wiki_id).first()  # 删除当前id内的wiki问题

        if not wiki_object:
            url = reverse("project:wiki", kwargs={"project_id": project_id})
            return redirect(url)
        form = WikiModelForm(request,instance=wiki_object)


        return render(request, "wiki_form.html", {"form":form})

    def post(self,request,project_id,wiki_id): #是因为需要修改然后就必须传递修改后的内容 所以instance所扮演的角色就是一个传递内容的容器.传递过去后
        #代替原有的或者没有的内容/
        wiki_object = Wiki.objects.filter(project_id=project_id, id=wiki_id).first()
        if not wiki_object:
            url = reverse("project:wiki", kwargs={"project_id": project_id})
            return redirect(url)
        form = WikiModelForm(request,data=request.POST,instance=wiki_object) # instance 可以说是结构化的数据相当于 QuerySet!
        if form.is_valid():

            if form.instance.parent:
                form.instance.depth = form.instance.parent.depth+1 #二级标签是父类的深度+自己的深度等于第三个深度
            else:
                form.instance.depth = 1
            form.save()
            url = reverse("project:wiki",kwargs={"project_id":project_id})
            preview_url = "{0}?wiki_id={1}".format(url,wiki_id)
            return redirect(preview_url)
        else:
            return render(request, "wiki_form.html", {"form": form})



def wiki(request,project_id):
    """wiki首页"""
    wiki_id = request.GET.get("wiki_id")

    if wiki_id:
        if not wiki_id.isdigit():
            return render(request, "wiki.html")
        wiki_object = Wiki.objects.filter(id=wiki_id,project_id=project_id).first()
        return render(request, "wiki.html",{"wiki_object":wiki_object})
    else:
        return render(request, "wiki.html")


def wiki_catalog(request,project_id):

    wikiitems = Wiki.objects.filter(project_id=project_id).values().order_by("depth","id")


    return JsonResponse({"status":True,"data":list(wikiitems)})


class Wiki_add(View):
    def get(self,request,project_id):
        form =WikiModelForm(request)
        return render(request, "wiki_form.html", {"form":form})


    def post(self,request,project_id):

        form = WikiModelForm(request,data=request.POST)
        if form.is_valid():
            if form.instance.parent:
                form.instance.depth = form.instance.parent.depth+1 #二级标签是父类的深度+自己的深度等于第三个深度
            else:
                form.instance.depth = 1
            form.instance.project = request.tracer.project
            form.save()
            url = reverse("project:wiki",kwargs={"project_id":project_id})
            return redirect(url)
        return render(request, "wiki_form.html", {"form": form, "error":form.errors})

@csrf_exempt
def wiki_upload(request,project_id):
    #插件上传图片

    image_obj = request.FILES.get("editormd-image-file")
    ext = image_obj.name.rsplit(".")[-1]
    key = "{}.{}".format(uid(request.tracer.user.mobile_phone),ext)

    image_url = upload_file(request.tracer.project.bucket,image_obj,key)
    print(image_url)

    result = {
        "success":1,
        "message":None,
        "url":image_url
    }
    return JsonResponse(result)

proj/templates/dashboard.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>
    概览

    </h1>
{% endblock %}

proj/templates/file.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>
文件
    </h1>
{% endblock %}

proj/templates/issues.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>
    问答

    </h1>
{% endblock %}

proj/templates/project_list.html
{% extends "layout/manage.html" %}

{% load static  %}


{% block css %}
    <style>
     .color-radio input[type="radio"]{
            opacity: 0;
            display: none;
     }

    .proj-title{
        width:200px;
        height:120px;
        padding:40px;
        color: white;
        font-size:20px;
    }
    .proj{
        width:200px;
        height:150px;
        border:1px solid lightgray;

        border-radius:4px;
        margin-left:40px;
        float:left;
    }
    .proj-info {
        padding:5px;
    }


    .color-radio label{
        margin-left: 0;
        padding-left: 0;
    }

    .color-radio input[type="radio"]{
        display: none;
    }
    .color-radio input[type="radio"]+.cycle{
        display: inline-block;
        height: 25px;
        width: 25px;
        border-radius: 50%;
        border:2px solid #dddddd;
    }

    .color-radio input[type="radio"]:checked +.cycle{
        border:1px solid black;
    }

    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid">
    <div style="margin: 10px 0;;">
        <a class="btn btn-primary" data-toggle="modal" data-target="#addModel"><i class="fa fa-plus" aria-hidden="true"></i>新建项目</a>
</div>
    </div>
    <div class="modal fade" id="addModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">创建项目</h4>
      </div>
      <div class="modal-body">
          <form id="addForm">
          {% csrf_token %}
              {% for form in forms %}
              <div class="form-group">
                <label for="{{ form.id_for_label }}">{{ form.label }}</label>


                {{ form }}


                <span class="error-msg"></span>
              </div>

              {% endfor %}


        </form>
      </div>
      <div class="modal-footer">
{#        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
        <button type="button" id="btnSubmit" class="btn btn-primary">确 定</button>
      </div>
    </div>
  </div>
</div>

<div>
        <div class="panel panel-default">
      <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i> 星标项目</div>
      <div class="panel-body">

        {% for item in project_dict.star %}
         <div class="item proj" id="cancel-star">
                <div class="proj-title" style="background-color: {{ item.get_color_display }};border-radius: 2px;">
                    <a href="{% url 'project:dashboard' project_id=item.id %}"  style="text-decoration: none"><p class="text-center" style="color:white;">{{ item.name }}</p></a>
                </div>

                <div class="info proj-info" >
                    <div style="float:left;margin-left:2px;" >
                        <a href="#" title="取消星标?" id="{{ item.id }}" class="cancel-star" style="text-decoration: none" type="button">
                           <i class="fa fa-star" aria-hidden="true"></i>
                        </a>
                        <span>{{ item.creator.username }}</span>
                    </div>
                    <div style="float:right;">
                        <i class="fa fa-user-o" aria-hidden="true"></i><span> {{ item.join_count }}</span>
                    </div>
                </div>
            </div>
          {% endfor %}

      </div>
    </div>
        <div class="panel panel-default">
      <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i> 我创建的</div>
      <div class="panel-body">

          {% for item in project_dict.my %}
              <div class="item proj">
                <div class="proj-title" style="background-color: {{ item.get_color_display }};border-radius: 2px;">
                    <a href="{% url 'project:dashboard' project_id=item.id %}" style="text-decoration: none" ><p class="text-center" style="color:white;">{{ item.name }}</p></a>
                </div>

                <div class="info proj-info" >
                    <div style="float:left;margin-left:2px;" >
                        <a href="#" title="是否星标?" class="add-star" id="{{ item.id }}" style="text-decoration: none" type="button">
                           <i class="fa fa-star-o" aria-hidden="true"></i>
                        </a>
                        <span>{{ item.creator.username }}</span>
                    </div>
                    <div style="float:right;">
                        <i class="fa fa-user-o" aria-hidden="true"></i><span> {{ item.join_count }}</span>
                    </div>
                </div>
            </div>
          {% endfor %}

      </div>
    </div>

          <div class="panel panel-default">
      <div class="panel-heading"><i class="fa fa-users" aria-hidden="true"></i> 我参与的</div>
      <div class="panel-body">

        {% for item in project_dict.join %}
            <div class="item proj">
                <div class="proj-title" style="background-color: {{ item.get_color_display }};border-radius: 2px;" class="add-star" id="{{ item.id }}">
                    <a href="{% url 'project:dashboard' project_id=item.id %}" style="text-decoration: none"><p class="text-center" style="color:white;">{{ item.name }}</p></a>
                </div>

                <div class="info proj-info" >
                    <div style="float:left;margin-left:2px;" >
                        <a href="#" title="是否星标?" class="add-star" id="{{ item.id }}" style="text-decoration: none" type="button">
                           <i class="fa fa-star-o" aria-hidden="true"></i>
                        </a>
                        <span>{{ item.creator.username }}</span>
                    </div>
                    <div style="float:right;">
                        <i class="fa fa-user-o" aria-hidden="true"></i><span> {{ item.join_count }}</span>
                    </div>
                </div>
            </div>
          {% endfor %}

      </div>
    </div>
</div>

{% endblock %}

{% block js %}

    <script>
        $(function(){
            bindSubmit();
            addStar();
            cancelStar();
        });

        function bindSubmit(){
            $("#btnSubmit").click(function(){
                $.ajax({
                    url:"{% url 'project:project_list' %}",
                    data:$("#addForm").serialize(),
                    type:"POST",
                    dataType:"JSON",
                    async:true,
                    success:function(res){
                        if(res.status){
                            location.reload(); //刷新
                        }else{
                            $.each(res.error,function(key,value){ //.each()循环信息 将参数1的dict信息给进行循环
                                    $("#id_"+key).next().text(value[0]);//
                                })
                        }

                    }
                })
            });
        }


        function addStar(){
        //        添加星标
            $(".add-star").click(function(){
                $.ajax({
                url:"{% url 'project:addstar' %}",
                data:{addstar:$(this).attr("id"),
                    "csrfmiddlewaretoken":"{{ csrf_token }}"
                },
                dateType: "JSON",
                type:"POST",
                success:function(res){
                    if (res){
                        location.reload();
                    }
                }
            })
        })

        }

        function cancelStar(){
        //   取消星标
            $(".cancel-star").click(function(){
                    $.ajax({
                    url:"{% url 'project:cancelStar' %}",
                    data:{cancelstar:$(this).attr("id"),
                        "csrfmiddlewaretoken":"{{ csrf_token }}"
                    },
                    dateType: "JSON",
                    type:"POST",
                    success:function(res){
                        if (res){
                            location.reload();
                        }
                    }
                })
            })

        }
    </script>

{% endblock %}

proj/templates/setting.html
{% extends 'layout/manage.html' %}

{% block content %}
    <h1>
    设置

    </h1>
{% endblock %}

proj/templates/statistics.html
{% extends 'layout/manage.html' %}

{% block content %}

    <h1>
    统计

    </h1>
{% endblock %}

proj/templates/wiki.html
{% extends 'layout/manage.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugin/editor.md/css/editormd.preview.min.css' %}">
    <style>
    .title-list{
        border-right: 1px solid #dddddd;
        min-height: 500px;
    }
    .panel-default .panel-heading{
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }
    .content {
         border-left: 1px solid #dddddd;
        min-height: 600px;
        margin-left:-1px;
    }
    .title-list ul{
        padding-left: 15px;
    }
    .title-list ul a{
        display: block;
        padding:5px 0;
    }

    {#.panel-body{#}
    {#    padding:0;#}

    </style>
{% endblock %}
{% block content %}


    <div class="container-fluid">
        <div class="panel panel-default">
          <div class="panel-heading">
              <div>
                  <i class="fa fa-book" aria-hidden="true"></i> wiki文档
              </div>


             <div class="function">
                 {% if wiki_object.id %}
                        <a href="{% url 'project:wiki_delete' project_id=request.tracer.project.id del_id=wiki_object.id %}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o" aria-hidden="true"></i> 删除</a>
                  <a href="{% url 'project:edit_wiki' project_id=request.tracer.project.id wiki_id=wiki_object.id %}" class="btn btn-primary btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 编辑</a>
                        <a href="{% url 'project:wiki_add' project_id=request.tracer.project.id %}" type="button" class="btn btn-success btn-xs"><i class="fa fa-plus-circle"></i> 新建</a>
                 {% else %}

                  <a href="{% url 'project:wiki_add' project_id=request.tracer.project.id %}" type="button" class="btn btn-success btn-xs"><i class="fa fa-plus-circle"></i> 新建</a>
                {% endif %}
             </div>
          </div>

            <div class="panel-body">
                <div class="col-sm-3 title-list">
                    <ul id="catalog">

                    </ul>
                </div>
                <div class="col-sm-9 content">
                    <div style="text-align: center;margin-top:50px;">
                        {% if wiki_object %}
                            <div id="previewMarkdown">
                                <textarea>
                                    {{ wiki_object.content }}
                                </textarea>

                            </div>

                        {% else %}
                        <h4>《{{ request.tracer.project.name }}》wiki文档库</h4>
                        <a href="{% url 'project:wiki_add' project_id=request.tracer.project.id %}" ><i class="fa fa-plus-circle"></i>
                                新建文章
                        </a>
                        {% endif %}
                    </div>
                </div>

    </div>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script src="{% static 'plugin/editor.md/editormd.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/prettify.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/raphael.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/underscore.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/marked.min.js' %}"></script>
    <script src="{% static 'plugin/editor.md/lib/jquery.flowchart.min.js' %}"></script>

    <script>

    var WIKI_DETAIL_URL = "{% url 'project:wiki' project_id=request.tracer.project.id %}";
    $(function(){
        initCatalog();
        initPreviewMarkDown();

        {#alert("{{ wiki_object.id }}");#}
    });
        function initPreviewMarkDown(){
                editormd.markdownToHTML("previewMarkdown",
                    {
                        htmlDecode:"style,script,iframe"
                    })
        }


        function initCatalog(){
            $.ajax({
                url:"{% url 'project:wiki_catalog' project_id=request.tracer.project.id %}",
                type:"GET",
                dataType:"JSON",
                success:function (res) {

                    if (res){
                        $.each(res.data,function(index,item){
                            var href = WIKI_DETAIL_URL+"?wiki_id="+item.id;
                            var li = $("<li>").attr("id","id_"+item.id).append($("<a>").text(item.title).attr("href",href)).append($("<ul>"));
                         if (!item.parent_id){

                             $("#catalog").append(li);
                         }else{

                             $("#id_"+item.parent_id).children("ul").append(li);
                         }

                        });
                    }else{
                        alert("初始化目录失败")
                    }
                }
            })
        }
    </script>

{% endblock %}