SaaS_System/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/',include("proj.urls",namespace="project")),
    path('users/',include('users.urls',namespace="users")),
    path("index/", TemplateView.as_view(template_name="../templates/index.html"), name="index"),
    path("mdeditor/",include("mdeditor.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/urls.py
from django.urls import path,include

from .views import project,proj_manage,wiki
app_name = "project"
urlpatterns = [
    # 项目列表
    path("list/", project.ProjectView.as_view(), name="project_list"),
    path("add_star/",project.addStar,name="addstar"),
    path("cancel_star/",project.cancelStar,name="cancelStar"),

    # 项目管理 完成项目才是关键
    path("manage/<project_id>/dashboard/", proj_manage.dashboard, name="dashboard"),
    path("manage/<project_id>/issues/", proj_manage.issues, name="issues"),
    path("manage/<project_id>/statistics/", proj_manage.statistics, name="statistics"),
    path("manage/<project_id>/file/", proj_manage.file, name="file"),

    path("manage/<project_id>/wiki/", wiki.wiki, name="wiki"),
    path("manage/<project_id>/wiki/upload/", wiki.wiki_upload, name="wiki_upload"),
    path("manage/<project_id>/wiki/add/",wiki.Wiki_add.as_view(),name="wiki_add"),
    path("manage/<project_id>/wiki/catalog/",wiki.wiki_catalog,name="wiki_catalog"),
    path("manage/<project_id>/wiki/delete/<del_id>",wiki.wiki_delete,name="wiki_delete"),
    path("manage/<project_id>/wiki/edit/<wiki_id>",wiki.EditWiki.as_view(),name="edit_wiki"),

    path("manage/<project_id>/setting/", proj_manage.setting, name="setting"),

]

users/urls.py
#coding:utf-8


from django.urls import path

from users.views import account

app_name = "users"
urlpatterns = [
    path('register/', account.RegisterView.as_view(), name="register"), #注册
    path('send_code/', account.sendcode, name="sendcode"),#获取验证码
    path('emaillogin/',account.EmailLoginView.as_view(),name="emaillogin"), #邮箱登录
    path('pswdlogin/',account.PswdLoginView.as_view(),name="pswdlogin"), #密码登录
    path("verify_img/",account.verify_picture,name="verify_picture"),
    path("logout/",account.logout,name="logout")
]

templates/layout/basic.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/3.4.1.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/font-awesome/css/font-awesome.min.css' %}">

    <style>
        .navbar-default{
            border-radius:0;

        }


    </style>
    {% block css %}{% endblock %}


</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">Tracer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="#">产品功能 <span class="sr-only"></span></a></li>
        <li><a href="#">企业方案</a></li>
        <li><a href="#">帮助文档</a></li>
        <li><a href="#">价格</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if request.tracer.user %}
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              {{ request.tracer.user.username }}<span class="caret"></span>
          </a>
              <ul class="dropdown-menu">
                    <li><a href="{% url 'project:project_list' %}">管理中心</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'users:logout' %}">退 出</a></li>
              </ul>
        </li>
          {% else %}
          <li><a href="{% url 'users:pswdlogin' %}">登 录</a></li>
          <li><a href="{% url 'users:register' %}">注 册</a></li>
          {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}
{% block js %}{% endblock %}
<script src="{% static 'plugin/jquery/jquery3.5.1.min.js' %}"></script>
<script src="{% static 'plugin/bootstrap/3.4.1.js.bootstrap.min.js' %}"></script>
</body>
</html>

templates/layout/manage.html
{% load static  %}
{% load project_inclusion_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/3.4.1.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/font-awesome/css/font-awesome.min.css' %}">

    <style>
        .error-msg{
        color:red;
        position:absolute;
        font-size:13px
    }

    </style>
    {% block css %}{% endblock %}


</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'project:project_list' %}">Tracer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
    {% all_project_list request %}
    {% if request.tracer.project %}
        <ul class="nav navbar-nav">
        {% manage_menu_list request %}
    {#        <li><a href="{% url 'project:dashboard' request.tracer.project.id %}">概览</a></li>#}
    {#        <li><a href="{% url 'project:issues' request.tracer.project.id %}">问题</a></li>#}
    {#        <li><a href="{% url 'project:wiki' request.tracer.project.id %}">wiki</a></li>#}
    {#        <li><a href="{% url 'project:statistics' request.tracer.project.id%}">统计</a></li>#}
    {#        <li><a href="{% url 'project:file' request.tracer.project.id %}">文件</a></li>#}
    {#        <li><a href="{% url 'project:setting' request.tracer.project.id%} ">配置</a></li>#}
        </ul>
    {% endif %}

      <ul class="nav navbar-nav navbar-right">
          <li><a href="#" ><i class="fa fa-calendar" aria-hidden="true"></i></a></li>
          <li><a href="#"><i class="fa fa-bell" aria-hidden="true"></i></a></li>

          <li><a href="#"><i class="fa fa-question-circle-o" aria-hidden="true"></i></a></li>

            {% if request.tracer.user %}
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  {{ request.tracer.user.username }}<span class="caret"></span>
              </a>
                  <ul class="dropdown-menu">
                        <li><a href="{% url 'index' %}">官 网</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'users:logout' %}">退 出</a></li>
                  </ul>
            </li>
              {% else %}
                  <li><a href="{% url 'users:pswdlogin' %}">登 录</a></li>
                  <li><a href="{% url 'users:register' %}">注 册</a></li>
              {% endif %}

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}
<script src="{% static 'plugin/jquery/jquery3.5.1.min.js' %}"></script>
<script src="{% static 'plugin/bootstrap/3.4.1.js.bootstrap.min.js' %}"></script>
{% block js %}

{% endblock %}

</body>
</html>